
/* Drop Tables */

DROP TABLE P_AUTH CASCADE CONSTRAINTS;
DROP TABLE P_BOARDATTACH CASCADE CONSTRAINTS;
DROP TABLE P_REPORT CASCADE CONSTRAINTS;
DROP TABLE P_BOARD CASCADE CONSTRAINTS;
DROP TABLE P_FOLLOW CASCADE CONSTRAINTS;
DROP TABLE P_GAME_TAG CASCADE CONSTRAINTS;
DROP TABLE P_REVIEW CASCADE CONSTRAINTS;
DROP TABLE P_GAME CASCADE CONSTRAINTS;
DROP TABLE P_NIJI_TAG CASCADE CONSTRAINTS;
DROP TABLE P_PAY CASCADE CONSTRAINTS;
DROP TABLE P_NIJI CASCADE CONSTRAINTS;
DROP TABLE P_SOUDAN CASCADE CONSTRAINTS;
DROP TABLE P_MEMBER CASCADE CONSTRAINTS;
DROP TABLE P_GRADE CASCADE CONSTRAINTS;
DROP TABLE P_NEWS CASCADE CONSTRAINTS;

/* Create Tables */

-- 회원인증
CREATE TABLE P_AUTH
(
	-- 유저아이디
	USERID varchar2(50) NOT NULL,
	-- 인증
	AUTH varchar2(50) NOT NULL,
	PRIMARY KEY (USERID)
);


-- 자유게시판
CREATE TABLE P_BOARD
(
	-- 게시물 번호
	BNO varchar2(20) NOT NULL,
	-- 제목
	TITLE varchar2(50) NOT NULL,
	-- 내용
	CONTENT varchar2(1000) NOT NULL,
	-- 작성자
	WRITER varchar2(50) NOT NULL,
	-- 등록일자
	REGDATE date DEFAULT SYSDATE NOT NULL,
	-- 수정일자
	UPDATEDATE date,
	PRIMARY KEY (BNO)
);

CREATE SEQUENCE seq_board NOCACHE;


-- 게시판 파일첨부
CREATE TABLE P_BOARDATTACH
(
	-- 파일번호
	UUID varchar2(20) NOT NULL,
	-- 업로드경로
	UPLOADPATH varchar2(100) NOT NULL,
	-- 파일이름
	FILENAME varchar2(30) NOT NULL,
	-- 파일타입
	FILETYPE varchar2(30) NOT NULL,
	-- 게시물번호
	BNO varchar2(20) NOT NULL,
	PRIMARY KEY (UUID)
);


-- 팔로우/팔로워
CREATE TABLE P_FOLLOW
(
	-- 팔로우 번호
	FNO varchar2(20) NOT NULL,
	-- 팔로우 유저 아이디
	FOLLOW_USERID varchar2(50) NOT NULL,
	-- 팔로워 유저 아이디
	FOLLOWER_USERid varchar2(50) NOT NULL,
	-- 등록일자
	REGDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (FNO)
);


CREATE SEQUENCE seq_follow NOCACHE;


-- 게임
CREATE TABLE P_GAME
(
	-- 게임번호
	GNO varchar2(30) NOT NULL,
	-- 게임 아이디
	GAMEID varchar2(30) NOT NULL,
	-- 게임 이미지
	GAME_IMG varchar2(30) NOT NULL,
	-- 게임 이름
	GAMENM varchar2(50) NOT NULL,
	-- 게임 가격
	GAME_PRICE varchar2(50) NOT NULL,
	-- 평균 별점
	AVG_SCORE number,
	-- 게임 설명
	GAME_DES varchar2(1000),
	-- 게임 트레일러
	GAME_VID varchar2(100),
	-- 제작사
	GAME_COMPANY varchar2(30),
	-- 선호 연령
	GAME_AGE varchar2(20),
	-- 게임 링크
	GAME_URL varchar2(100),
	-- 등록일
	REGDATE date,
	-- 업데이트일자
	UPDATEDATE date,
	PRIMARY KEY (GNO)
);


CREATE SEQUENCE seq_game NOCACHE;


-- 태그
CREATE TABLE P_GAME_TAG
(
	-- 게임 번호
	GNO varchar2(30) NOT NULL,
	-- 태그아이디
	TAGNAME varchar2(50) NOT NULL,
	PRIMARY KEY (GNO)
);


-- 등급 관리
CREATE TABLE P_GRADE
(
	-- 등급코드
	GRADE_CODE varchar2(20) NOT NULL,
	-- 등급명
	GRADE_NAME varchar2(20) DEFAULT '브론즈' NOT NULL,
	-- 등급이미지
	GRADE_IMG varchar2(30) NOT NULL,
	-- 등급레벨
	GRADE_LV number DEFAULT 0 NOT NULL,
	PRIMARY KEY (GRADE_CODE)
);


-- 회원
CREATE TABLE P_MEMBER
(
	-- 아이디
	USER_ID varchar2(50) NOT NULL,
	-- USER_PW
	USER_PW varchar2(30) NOT NULL,
	-- 닉네임
	NICKNAME varchar2(50) NOT NULL,
	-- 이메일
	EMAIL varchar2(50) NOT NULL,
	-- 생년월일
	BIRTH date,
	-- 등급코드
	GRADECODE varchar2(20),
	-- 이미지
	IMG varchar2(50),
	-- 성별
	GENDER char,
	-- 마지막로그인
	LASTLOGIN date,
	-- 계좌
	ACCOUNT varchar2(30),
	-- 가입일자
	REGDATE date NOT NULL,
	-- 수정일자
	UPDATEDATE date,
	-- 당일 로그인 확인
	ENABLED varchar2(20),
	PRIMARY KEY (USER_ID)
);


-- 게임 뉴스
CREATE TABLE P_NEWS
(
	-- 뉴스 번호
	NEWSNO varchar2(20) NOT NULL,
	-- 뉴스 제목
	TITLE varchar2(100),
	-- 내용
	CONTENT varchar2(100),
	-- 등록일
	REGDATE date DEFAULT SYSDATE,
	PRIMARY KEY (RNO)
);

CREATE SEQUENCE seq_NEWS NOCACHE;



-- 거래테이블
CREATE TABLE P_NIJI
(
	-- 거래글NO
	NNO varchar2(20) NOT NULL,
	-- 제목
	TITLE varchar2(30) NOT NULL,
	-- 내용
	CONTENT varchar2(1000) NOT NULL,
	-- 분류
	CATEGORY varchar2(10) NOT NULL,
	-- 이미지
	IMG varchar2(50),
	-- 가격
	PRICE number NOT NULL,
	-- 작성자
	WRITER varchar2(50) NOT NULL,
	-- 등록일
	REGDATE date DEFAULT SYSDATE NOT NULL,
	-- 수정일
	UPDATEDATE date,
	PRIMARY KEY (NNO)
);

CREATE SEQUENCE seq_NIJI NOCACHE;

-- 거래 태그
CREATE TABLE P_NIJI_TAG
(
	-- 거래NO
	NNO varchar2(20) NOT NULL,
	-- 태그 아이디
	TAGNAME varchar2(20) NOT NULL,
	PRIMARY KEY (NNO)
);


-- 결제테이블
CREATE TABLE P_PAY
(
	-- 결제NO
	PNO varchar2(20) NOT NULL,
	-- 거래NO
	NNO varchar2(20) NOT NULL,
	-- 제목
	TITLE varchar2(50) NOT NULL,
	-- 내용
	CONTENT varchar2(1000) NOT NULL,
	-- 이미지
	IMG varchar2(50),
	-- 판매자
	SELLER varchar2(50) NOT NULL,
	-- 구매자
	BUYER varchar2(50) NOT NULL,
	-- 구매자이메일
	BUYER_EMAIL varchar2(50) NOT NULL,
	-- 구매상태
	PAY_STATUS number(1),
	-- 가격
	PRICE number,
	-- 등록일
	REGDATE date DEFAULT SYSDATE,
	-- 수정일
	UPDATEDATE date,
	PRIMARY KEY (PNO)
);

CREATE SEQUENCE seq_PAY NOCACHE;


-- 신고 테이블
CREATE TABLE P_REPORT
(
	-- 신고NO
	REPORT_NO varchar2(20) NOT NULL,
	-- 신고자
	ACTIVE_USERID varchar2(50) NOT NULL,
	-- 피신고자
	PASSIVE_USERID varchar2(50) NOT NULL,
	-- 게시물NO
	BNO varchar2(20) NOT NULL,
	-- 카테고리
	CATEGORY varchar2(30) NOT NULL,
	-- 등록일
	REGDATE date,
	-- 상태
	STATUS number(1) NOT NULL,
	PRIMARY KEY (REPORT_NO)
);

CREATE SEQUENCE seq_REPORT NOCACHE;


-- 리뷰
CREATE TABLE P_REVIEW
(
	-- 리뷰 번호
	RNO varchar2(20) NOT NULL,
	-- 내용
	CONTENT varchar2(1000),
	-- 작성자
	WRITER varchar2(50) NOT NULL,
	-- 게임 번호
	GNO varchar2(30) NOT NULL,
	-- 별점
	SCORE number,
	-- 등록일
	REGDATE date,
	-- 업데이트일자
	UPDATEDATE date,
	PRIMARY KEY (RNO)
);

CREATE SEQUENCE seq_REVIEW NOCACHE;

-- 고객센터 1:1 상담
CREATE TABLE P_SOUDAN
(
	-- 상담 번호
	QNO varchar2(20) NOT NULL,
	-- 질문자
	QUESTIONER varchar2(50) NOT NULL,
	-- 답변자
	ANSWERER varchar2(50),
	-- 질문내용
	Q_CONTENT varchar2(1000) NOT NULL,
	-- 답변내용
	A_CONTENT varchar2(1000),
	-- 질문 등록일
	Q_REGDATE date NOT NULL,
	-- 답변 등록일
	A_REGDATE date,
	PRIMARY KEY (QNO)
);

CREATE SEQUENCE seq_SOUDAN NOCACHE;

/* Create Foreign Keys */

ALTER TABLE P_BOARDATTACH
	ADD FOREIGN KEY (BNO)
	REFERENCES P_BOARD (BNO)
;


ALTER TABLE P_REPORT
	ADD FOREIGN KEY (BNO)
	REFERENCES P_BOARD (BNO)
;


ALTER TABLE P_GAME_TAG
	ADD FOREIGN KEY (GNO)
	REFERENCES P_GAME (GNO)
;


ALTER TABLE P_REVIEW
	ADD FOREIGN KEY (GNO)
	REFERENCES P_GAME (GNO)
;


ALTER TABLE P_MEMBER
	ADD FOREIGN KEY (GRADECODE)
	REFERENCES P_GRADE (GRADE_CODE)
;


ALTER TABLE P_AUTH
	ADD FOREIGN KEY (USERID)
	REFERENCES P_MEMBER (USER_ID)
;


ALTER TABLE P_BOARD
	ADD FOREIGN KEY (WRITER)
	REFERENCES P_MEMBER (USER_ID)
;


ALTER TABLE P_FOLLOW
	ADD FOREIGN KEY (FOLLOW_USERID)
	REFERENCES P_MEMBER (USER_ID)
;


ALTER TABLE P_FOLLOW
	ADD FOREIGN KEY (FOLLOWER_USERid)
	REFERENCES P_MEMBER (USER_ID)
;


ALTER TABLE P_NIJI
	ADD FOREIGN KEY (WRITER)
	REFERENCES P_MEMBER (USER_ID)
;


ALTER TABLE P_PAY
	ADD FOREIGN KEY (BUYER)
	REFERENCES P_MEMBER (USER_ID)
;


ALTER TABLE P_REPORT
	ADD FOREIGN KEY (ACTIVE_USERID)
	REFERENCES P_MEMBER (USER_ID)
;


ALTER TABLE P_REVIEW
	ADD FOREIGN KEY (WRITER)
	REFERENCES P_MEMBER (USER_ID)
;


ALTER TABLE P_SOUDAN
	ADD FOREIGN KEY (QUESTIONER)
	REFERENCES P_MEMBER (USER_ID)
;


ALTER TABLE P_SOUDAN
	ADD FOREIGN KEY (ANSWERER)
	REFERENCES P_MEMBER (USER_ID)
;


ALTER TABLE P_NIJI_TAG
	ADD FOREIGN KEY (NNO)
	REFERENCES P_NIJI (NNO)
;


ALTER TABLE P_PAY
	ADD FOREIGN KEY (NNO)
	REFERENCES P_NIJI (NNO)
;





/* Comments */

COMMENT ON TABLE P_AUTH IS '회원인증';
COMMENT ON COLUMN P_AUTH.USERID IS '유저아이디';
COMMENT ON COLUMN P_AUTH.AUTH IS '인증';
COMMENT ON TABLE P_BOARD IS '자유게시판';
COMMENT ON COLUMN P_BOARD.BNO IS '게시물 번호';
COMMENT ON COLUMN P_BOARD.TITLE IS '제목';
COMMENT ON COLUMN P_BOARD.CONTENT IS '내용';
COMMENT ON COLUMN P_BOARD.WRITER IS '작성자';
COMMENT ON COLUMN P_BOARD.REGDATE IS '등록일자';
COMMENT ON COLUMN P_BOARD.UPDATEDATE IS '수정일자';
COMMENT ON TABLE P_BOARDATTACH IS '게시판 파일첨부';
COMMENT ON COLUMN P_BOARDATTACH.UUID IS '파일번호';
COMMENT ON COLUMN P_BOARDATTACH.UPLOADPATH IS '업로드경로';
COMMENT ON COLUMN P_BOARDATTACH.FILENAME IS '파일이름';
COMMENT ON COLUMN P_BOARDATTACH.FILETYPE IS '파일타입';
COMMENT ON COLUMN P_BOARDATTACH.BNO IS '게시물번호';
COMMENT ON TABLE P_FOLLOW IS '팔로우/팔로워';
COMMENT ON COLUMN P_FOLLOW.FNO IS '팔로우 번호';
COMMENT ON COLUMN P_FOLLOW.FOLLOW_USERID IS '팔로우 유저 아이디';
COMMENT ON COLUMN P_FOLLOW.FOLLOWER_USERid IS '팔로워 유저 아이디';
COMMENT ON COLUMN P_FOLLOW.REGDATE IS '등록일자';
COMMENT ON TABLE P_GAME IS '게임';
COMMENT ON COLUMN P_GAME.GNO IS '게임번호';
COMMENT ON COLUMN P_GAME.GAMEID IS '게임 아이디';
COMMENT ON COLUMN P_GAME.GAME_IMG IS '게임 이미지';
COMMENT ON COLUMN P_GAME.GAMENM IS '게임 이름';
COMMENT ON COLUMN P_GAME.GAME_PRICE IS '게임 가격';
COMMENT ON COLUMN P_GAME.AVG_SCORE IS '평균 별점';
COMMENT ON COLUMN P_GAME.GAME_DES IS '게임 설명';
COMMENT ON COLUMN P_GAME.GAME_VID IS '게임 트레일러';
COMMENT ON COLUMN P_GAME.GAME_COMPANY IS '제작사';
COMMENT ON COLUMN P_GAME.GAME_AGE IS '선호 연령';
COMMENT ON COLUMN P_GAME.GAME_URL IS '게임 링크';
COMMENT ON COLUMN P_GAME.REGDATE IS '등록일';
COMMENT ON COLUMN P_GAME.UPDATEDATE IS '업데이트일자';
COMMENT ON TABLE P_GAME_TAG IS '태그';
COMMENT ON COLUMN P_GAME_TAG.GNO IS '게임 번호';
COMMENT ON COLUMN P_GAME_TAG.TAGNAME IS '태그이름';
COMMENT ON TABLE P_GRADE IS '등급 관리';
COMMENT ON COLUMN P_GRADE.GRADE_CODE IS '등급코드';
COMMENT ON COLUMN P_GRADE.GRADE_NAME IS '등급명';
COMMENT ON COLUMN P_GRADE.GRADE_IMG IS '등급이미지';
COMMENT ON COLUMN P_GRADE.GRADE_LV IS '등급레벨';
COMMENT ON TABLE P_MEMBER IS '회원';
COMMENT ON COLUMN P_MEMBER.USER_ID IS '아이디';
COMMENT ON COLUMN P_MEMBER.USER_PW IS 'USER_PW';
COMMENT ON COLUMN P_MEMBER.NICKNAME IS '닉네임';
COMMENT ON COLUMN P_MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN P_MEMBER.BIRTH IS '생년월일';
COMMENT ON COLUMN P_MEMBER.GRADECODE IS '등급코드';
COMMENT ON COLUMN P_MEMBER.IMG IS '이미지';
COMMENT ON COLUMN P_MEMBER.GENDER IS '성별';
COMMENT ON COLUMN P_MEMBER.LASTLOGIN IS '마지막로그인';
COMMENT ON COLUMN P_MEMBER.ACCOUNT IS '계좌';
COMMENT ON COLUMN P_MEMBER.REGDATE IS '가입일자';
COMMENT ON COLUMN P_MEMBER.UPDATEDATE IS '수정일자';
COMMENT ON COLUMN P_MEMBER.ENABLED IS '당일 로그인 확인';
COMMENT ON TABLE P_NEWS IS '게임 뉴스';
COMMENT ON COLUMN P_NEWS.NEWSNO IS '뉴스 번호';
COMMENT ON COLUMN P_NEWS.TITLE IS '뉴스 제목';
COMMENT ON COLUMN P_NEWS.CONTENT IS '내용';
COMMENT ON COLUMN P_NEWS.REGDATE IS '등록일';
COMMENT ON TABLE P_NIJI IS '거래테이블';
COMMENT ON COLUMN P_NIJI.NNO IS '거래글NO';
COMMENT ON COLUMN P_NIJI.TITLE IS '제목';
COMMENT ON COLUMN P_NIJI.CONTENT IS '내용';
COMMENT ON COLUMN P_NIJI.CATEGORY IS '분류';
COMMENT ON COLUMN P_NIJI.IMG IS '이미지';
COMMENT ON COLUMN P_NIJI.PRICE IS '가격';
COMMENT ON COLUMN P_NIJI.WRITER IS '작성자';
COMMENT ON COLUMN P_NIJI.REGDATE IS '등록일';
COMMENT ON COLUMN P_NIJI.UPDATEDATE IS '수정일';
COMMENT ON TABLE P_NIJI_TAG IS '거래 태그';
COMMENT ON COLUMN P_NIJI_TAG.NNO IS '거래NO';
COMMENT ON COLUMN P_NIJI_TAG.TAGNAME IS '태그이름';
COMMENT ON TABLE P_PAY IS '결제테이블';
COMMENT ON COLUMN P_PAY.PNO IS '결제NO';
COMMENT ON COLUMN P_PAY.NNO IS '거래NO';
COMMENT ON COLUMN P_PAY.TITLE IS '제목';
COMMENT ON COLUMN P_PAY.CONTENT IS '내용';
COMMENT ON COLUMN P_PAY.IMG IS '이미지';
COMMENT ON COLUMN P_PAY.SELLER IS '판매자';
COMMENT ON COLUMN P_PAY.BUYER IS '구매자';
COMMENT ON COLUMN P_PAY.BUYER_EMAIL IS '구매자이메일';
COMMENT ON COLUMN P_PAY.PAY_STATUS IS '구매상태';
COMMENT ON COLUMN P_PAY.PRICE IS '가격';
COMMENT ON COLUMN P_PAY.REGDATE IS '등록일';
COMMENT ON COLUMN P_PAY.UPDATEDATE IS '수정일';
COMMENT ON TABLE P_REPORT IS '신고 테이블';
COMMENT ON COLUMN P_REPORT.REPORT_NO IS '신고NO';
COMMENT ON COLUMN P_REPORT.ACTIVE_USERID IS '신고자';
COMMENT ON COLUMN P_REPORT.PASSIVE_USERID IS '피신고자';
COMMENT ON COLUMN P_REPORT.BNO IS '게시물NO';
COMMENT ON COLUMN P_REPORT.CATEGORY IS '카테고리';
COMMENT ON COLUMN P_REPORT.REGDATE IS '등록일';
COMMENT ON COLUMN P_REPORT.STATUS IS '상태';
COMMENT ON TABLE P_REVIEW IS '리뷰';
COMMENT ON COLUMN P_REVIEW.RNO IS '리뷰 번호';
COMMENT ON COLUMN P_REVIEW.CONTENT IS '내용';
COMMENT ON COLUMN P_REVIEW.WRITER IS '작성자';
COMMENT ON COLUMN P_REVIEW.GNO IS '게임 번호';
COMMENT ON COLUMN P_REVIEW.SCORE IS '별점';
COMMENT ON COLUMN P_REVIEW.REGDATE IS '등록일';
COMMENT ON COLUMN P_REVIEW.UPDATEDATE IS '업데이트일자';
COMMENT ON TABLE P_SOUDAN IS '고객센터 1:1 상담';
COMMENT ON COLUMN P_SOUDAN.QNO IS '상담 번호';
COMMENT ON COLUMN P_SOUDAN.QUESTIONER IS '질문자';
COMMENT ON COLUMN P_SOUDAN.ANSWERER IS '답변자';
COMMENT ON COLUMN P_SOUDAN.Q_CONTENT IS '질문내용';
COMMENT ON COLUMN P_SOUDAN.A_CONTENT IS '답변내용';
COMMENT ON COLUMN P_SOUDAN.Q_REGDATE IS '질문 등록일';
COMMENT ON COLUMN P_SOUDAN.A_REGDATE IS '답변 등록일';



